[package]
name = "exception_test"
version = "0.1.0"
authors = ["toby <coderhuang@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[profile.release]
# panic = 'abort'